#pragma once

template <class T>
class CProxy_IDataMgrEvents : public IConnectionPointImpl<T, &__uuidof( _IDataMgrEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
